[config]
[config.App]
Secret = 'ADSDWW1DSADSADSAWJJK'
HttpPort = 9022
OpcHost = '127.0.0.1'
OpcServer = 'opcserversim.Instance.1'
KeepConn = 1

[config.Zaplog]
Director = 'runtime/log'
Level = 'error'
