name: Build OPC Connector

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # 允许手动触发构建
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        architecture: 'x86' # 使用32位版本

    - name: Install dependencies
      run: |
        go mod tidy

    - name: Build 32-bit
      run: |
        set GOARCH=386
        go build -ldflags="-s -w" -o opcConnector-win32.exe

    - name: Build 64-bit
      run: |
        set GOARCH=amd64
        go build -ldflags="-s -w" -o opcConnector-win64.exe

    - name: Upload 32-bit artifact
      uses: actions/upload-artifact@v3
      with:
        name: opcConnector-win32
        path: opcConnector-win32.exe

    - name: Upload 64-bit artifact
      uses: actions/upload-artifact@v3
      with:
        name: opcConnector-win64
        path: opcConnector-win64.exe

    # 如果需要创建 Release
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          opcConnector-win32.exe
          opcConnector-win64.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 